language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck doxygen graphviz qt5-qmake qtbase5-dev
  - sudo apt-get install -qq lcov rubygems
  - gem install lcoveralls

install:
  # Fetch Qt 5.1's QMessageAuthenticationCode class, and dependencies, for Qt 5.0 support.
  - wget -P src/core/ https://code.qt.io/cgit/qt/qtbase.git/plain/src/3rdparty/rfc6234/sha-private.h
  - wget -P src/core/ https://code.qt.io/cgit/qt/qtbase.git/plain/src/3rdparty/rfc6234/sha.h
  - wget -P src/core/ https://code.qt.io/cgit/qt/qtbase.git/plain/src/3rdparty/rfc6234/sha224-256.c
  - wget -P src/core/ https://code.qt.io/cgit/qt/qtbase.git/plain/src/3rdparty/rfc6234/sha384-512.c
  - wget -P src/core/ https://code.qt.io/cgit/qt/qtbase.git/plain/src/corelib/tools/qmessageauthenticationcode.cpp
  - wget -P src/core/ https://code.qt.io/cgit/qt/qtbase.git/plain/src/corelib/tools/qmessageauthenticationcode.h
  # Fixup some includes / paths.
  - sed -i -re 's/"qvarlengtharray.h"/<QVarLengthArray>/' -e 's:\.\./\.\./3rdparty/rfc6234/::' src/core/qmessageauthenticationcode.cpp
  # No Sha3_* constants in Qt5.0
  - sed -i -re 's:(^\s*)(.*Sha3_):\1//\2:' src/core/qmessageauthenticationcode.cpp
  # Restore the rfc6234 code's original stdint types (Nokia commented them out).
  - sed -i -re 's:^#define u?int://&:' src/core/qmessageauthenticationcode.cpp
  - sed -i -re 's:^//\s*(#include <stdint.h>):\1:' src/core/sha.h
  # Restore the addTemp and SHA*AddLength macros (Nokia commented out / renamed).
  - sed -i -re 's:^/\*\s*(static.*addTemp;)\s*\*/:\1:' -e 's/(SHA224_256AddLength)M/\1/' src/core/sha224-256.c
  - sed -i -re 's:^/\*\s*(static.*addTemp;)\s*\*/:\1:' -e 's/(SHA384_512AddLength)M/\1/' src/core/sha384-512.c
  - cat src/core/sha224-256.c
  - cat src/core/sha384-512.c
  - cat src/core/qmessageauthenticationcode.cpp
  # Apply the QTBUG-32100 fixes for Qt 5.0 with Clang on Travis CI
  - sudo patch -p0 /usr/include/qt5/QtCore/qabstractitemmodel.h .travis/qabstractitemmodel.diff
  - sudo patch -p0 /usr/include/qt5/QtCore/qurl.h .travis/qurl.diff
  - sudo patch -p0 /usr/include/qt5/QtNetwork/qhostaddress.h .travis/qhostaddress.diff

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR-build
  - if [ "$CXX" = "clang++" ]; then export QMAKESPEC=linux-clang; fi
  - pushd "$TRAVIS_BUILD_DIR-build"
  - qmake -qt=qt5 -v
  - qmake -qt=qt5 -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"
  - popd

script:
  - cppcheck --error-exitcode=1 --quiet .
  - make -C "$TRAVIS_BUILD_DIR-build" all
  - make -C "$TRAVIS_BUILD_DIR-build" check

after_success:
  - make -C "$TRAVIS_BUILD_DIR-build/test/unit/all" coverage
  - sed -i -e 's|^SF:/home/travis/build/libqtaws|SF:TRAVIS_BUILD_DIR'
    "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"
  - lcoveralls --retry-count 5 --root "$TRAVIS_BUILD_DIR/src" --trace
    "$TRAVIS_BUILD_DIR-build/release/unit-test-all-tmp/coverage.info"
