language: cpp

os:
  - linux
  - osx

dist: trusty

compiler:
  - clang
  - gcc

matrix:
  exclude:
    # Qt 5.6+ no longer supports gcc on OS X.
    - { os: osx, compiler: gcc }

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository -y ppa:beineri/opt-qt57-trusty'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install cppcheck'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt57base'
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew install cppcheck qt55'
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew link --force qt$BREW'

before_script:
  - cppcheck --error-exitcode=1 --quiet src
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[ "$TRAVIS_OS_NAME" != linux ] || . /opt/qt57/bin/qt57-env.sh'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - pushd "$TRAVIS_BUILD_DIR-build"
  - qmake -v
  - qmake -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"
  - popd

script:
  - make -C "$TRAVIS_BUILD_DIR-build" all

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fbd7a436c2f67325cffc
