language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev

install:
  # Fetch Qt 5.1's QMessageAuthenticationCode class, and dependencies, for Qt 5.0 support.
  - wget -P src/core/ https://qt.gitorious.org/qt/qtbase/raw/src/3rdparty/rfc6234/sha-private.h
  - wget -P src/core/ https://qt.gitorious.org/qt/qtbase/raw/src/3rdparty/rfc6234/sha.h
  - wget -P src/core/ https://qt.gitorious.org/qt/qtbase/raw/src/3rdparty/rfc6234/sha224-256.c
  - wget -P src/core/ https://qt.gitorious.org/qt/qtbase/raw/src/3rdparty/rfc6234/sha384-512.c
  - wget -P src/core/ https://qt.gitorious.org/qt/qtbase/raw/src/corelib/tools/qmessageauthenticationcode.cpp
  - wget -P src/core/ https://qt.gitorious.org/qt/qtbase/raw/src/corelib/tools/qmessageauthenticationcode.h
  - sed -e 's:\.\./\.\./3rdparty/::' src/core/qmessageauthenticationcode.cpp

before_script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - false
  # Stop here for now.

script:
  - make
  - make check
